# Test Center - Compliance Testing Application (Client UI)
# Copyright (C) 2015 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# @license http://opensource.org/licenses/AGPL-3.0 Affero GNU Public License v3.0
# @copyright 2014 Paulo Ferreira
# @author Paulo Ferreira <pf at sourcenotes.org>

##
# Default Landing Pages
##
landing:
  
  ##
  # Default Page Settings
  ##
  default:
    inherit: 'default:standard'
    template: true
    group: landing
    page: 'page.php'
    includes:
      head: 'head.php'
      body: 'landing/body.php'
    css:
      styles:
        body: 
          background-color: '#F6E1D30'

  ##
  # Default Incoming Landing Page
  ##
  home:
    inherit: landing
    template: false
    title: 'PAGE:TITLE:LANDING:HOME'
    includes:
      menu: 
        file: 'landing/menus/home.php'
        required: ['semantic-sidebar', 'jquery-utils']
        js:
          files: 'common/menu.js'
          scripts:
            on-load: |
              initialize_menu('sb_menu','btn_menu');
      content: 'landing/home.php'
    required: ['site-js', 'crypto-js', 'jquery', 'jquery-transform', 'jquery-toaster', 'jquery-utils', 'services-js']
    js:
      files: ['common/session.js', 'common/forms.js', 'landing/home.js']
      scripts:
        on-load: |
          // Set the Number of Background Images
          window.__bg_image_count = 7;
          window.__bg_image_src = '/img/landing/';
          initialize();
    css: 'landing-home.css'

  ##
  # Default Settings for Logged In Pages
  ##
  left-menu:
    inherit: landing
    template: true
    includes:
      body: 'left-sidebar.php'
      lsidebar: 
        file: 'landing/menus/menu.php'
        required: ['site-js', 'semantic-sidebar', 'jquery-utils', 'services-js']
        js:
          files: 'common/menu.js'
          scripts:
            on-load: |
              initialize_menu('sb_menu','btn_menu');

  ##
  # Introduction Page
  ##
  introduction:
    inherit: 'landing:left-menu'
    template: false
    title: 'PAGE:TITLE:INSTITUTIONAL:INTRO'
    includes:
      content: 'landing/introduction.php'
    required: ['site-js', 'jquery', 'jquery-transform', 'jquery-toaster', 'jquery-utils', 'services-js']
    js:
      files: ['common/session.js']
#    css: 'landing-home.css'

  ##
  # Help Page
  ##
  help:
    inherit: 'landing:left-menu'
    template: false
    title: 'PAGE:TITLE:INSTITUTIONAL:HELP'
    includes:
      content: 'landing/help.php'
    required: ['site-js', 'crypto-js', 'jquery', 'jquery-transform', 'jquery-toaster', 'jquery-utils', 'services-js']
    js:
      files: ['common/session.js']
#    css: 'landing-home.css'
      