# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Run Entity (Properties Metadata)
##
run:
  default: 
    inherit: default
    data-direction: both
  id: 
    inherit: default:key
    data-direction: in
    label: ID
    description: Unique Run Identifier
    value: 
      type: integer
      auto: true
  project:
    inherit: ':reference'
    label: Project
    description: Project the Run Belongs To
    value: 
      auto: true
    reference:
      object: project
      key: project:id
    display:
      field: 'project:name'
  set:
    inherit: ':reference'
    label: Set
    description: Set Associated with this Run
    value: 
      auto: true
    reference:
      object: set
      key: set:id
    display:
      field: 'set:name'
  group:
    inherit: run:default
    label: Group
    description: Group the Run Belongs To
  name:
    inherit: run:default
    key: true
    label: Name
    description: Unique Run Name
  description:
    inherit: run:default
    label: Description
    description: Run Description
    value: 
      type: html
  state: 
    inherit: run:default
    label: State
    description: Current Run State
    value: 
      type: integer
  state_code: 
    inherit: run:default
    label: Code
    description: Run Execution Code
    value: 
      type: integer
  playlist_position:
    inherit: ':reference'
    label: Current Position
    description: Current Position in Play List
    value: 
      auto: true
      nullable: true
    reference:
      object: playlist
      key: playlist:id
    display:
      field: 'playlist:sequence'
  creator:
    inherit: ':reference'
    label: Creator
    description: User that created this Run
    value: 
      auto: true
      nullable: false
    reference:
      object: user
      key: user:id
    display:
      field: 'user:name'
  date_created:
    inherit: user:default
    label: Created
    description: Creation Date
    value: 
      type: datetime
      auto: true
      nullable: false
  last_modifier:
    inherit: ':reference'
    label: Last Modifier
    description: User that last modified this Run
    value: 
      auto: true
    reference:
      object: user
      key: user:id
    display:
      field: 'user:name'
  date_modified:
    inherit: user:default
    label: Last Modified
    description: Last Modification Date
    value: 
      type: datetime
      auto: true
  owner:
    inherit: ':reference'
    label: Owner
    description: User the owns the Run
    value: 
      auto: true
    reference:
      object: user
      key: user:id
    display:
      field: 'user:name'
    