# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Organinzation Service Definitions
##
organization:
  manage:
    inherit: default
    service: 
      - manage
      - org
    parameters:
      allow: 'organization:*'
    
  #
  # Create Organization Record
  # URL :
  # - manage/org/create/{organization:name}[?field=value-tuplet[&...]]
  #
  create:
    inherit: 'organization:manage'
    action: create
    key: 'organization:name'
    parameters:
      exclude: ['organization:id', 'organization:name']
  #
  # Read Organization Record
  # URL : 
  # - manage/org/read/{organization:id}   or
  # - manage/org/read/{organization:name}
  #
  read:    
    inherit: 'organization:manage'
    action: read
    keys:
      - 'organization:id'
      - 'organization:name'
    parameters:
      allow: none
  #
  # Update Organization Record
  # URL : 
  # - manage/org/read/{organization:id}?field=value-tuplet[&...]   or
  # - manage/org/read/{organization:name}?field=value-tuplet[&...]
  #
  update:
    inherit: 'organization:manage'
    action: update
    keys:
      - 'organization:id'
      - 'organization:name'
    parameters:
      require: true
      exclude: 'organization:id'
  #
  # Delete Organization Record
  # URL : 
  # - manage/org/delete/{organization:id}   or
  # - manage/org/delete/{organization:name}
  #
  delete:
    inherit: 'organization:manage'
    action: delete
    keys:
      - 'organization:id'
      - 'organization:name'
    parameters:
      allow: none
  #
  # List Organization Records
  # URL : 
  # - manage/orgs/list[?field=value-tuplet[&...]]
  #
  list: 
    inherit: 'organization:manage'
    service: 
      - manage
      - orgs
    action: list
    parameters: 
      allow: ['virtual:filter','virtual:sort','virtual:limit']
  #
  # Count Organization Records
  # URL : 
  # - manage/orgs/count[?field=value-tuplet[&...]]
  #
  count:
    inherit: 'organization:manage'
    service: 
      - manage
      - orgs
    action: count
    parameters:
      allow: ['virtual:filter']
  #
  # List the Organizations the Current Session User Belongs to
  # URL : 
  # - manage/orgs/list[?field=value-tuplet[&...]]
  #
  user_list: 
    inherit: 'organization:list'
    service: 
      - session
      - orgs
  #
  # Count the Organizations the Current Session User Belongs to
  # URL : 
  # - manage/orgs/count[?field=value-tuplet[&...]]
  #
  user_count:
    inherit: 'organization:count'
    service: 
      - session
      - orgs
    