# Test Center - Compliance Testing Application
# Copyright (C) 2012 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Meta Data (service path /meta)
##

# Retrieve Table Meta Data
meta_table:
    pattern:  /table/{id}
    defaults: { _controller: TestCenterServiceBundle:Metadata:table }

# Retrieve Form Meta Data
meta_form:
    pattern:  /form/{id}
    defaults: { _controller: TestCenterServiceBundle:Metadata:form}

# Retrieve A Single Field's Meta Data
# {id} of the field definition to return
meta_field:
    pattern:  /field/{id}
    defaults: { _controller: TestCenterServiceBundle:Metadata:field}

# Retrieve a List of Field's Meta Data
# {list} comma seperated list, of fields, for which the Meta data is required
#   the 'list' parameter, can also be provided as a GET/POST parameter
meta_fields:
    pattern:  /fields/{list}
    defaults: { _controller: TestCenterServiceBundle:Metadata:fields, list: null}

# Retrieve A Single Action's Meta Data
# {id} of the action definition to return
meta_action:
    pattern:  /action/{id}
    defaults: { _controller: TestCenterServiceBundle:Metadata:action}

# Retrieve a List of Actions Meta Data
# {list} comma seperated list, of actions, for which the Meta data is required
#   the 'list' parameter, can also be provided as a GET/POST parameter
meta_actions:
    pattern:  /actions/{list}
    defaults: { _controller: TestCenterServiceBundle:Metadata:actions, list: null}
