# Test Center - Compliance Testing Application
# Copyright (C) 2012 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Default Table (Metadata Model)
##
table:
  default:
    title: 'Table'
    #
    # Datastore Information
    #
    datastore:
      # Source : Can be an Static Array of Row Values or a Dynamically Loaded URL
      source: ~
      # Source : Fields List
      fields: ~
    #
    # Table Display Properties
    #
    # Columns to Display
    columns: ~
    # Initially Hidden Columns
    hidden: ~
    # Is Sortable?
    sortable: false
    # Columns that can be sorted
    sort-on: ~
    # Is Filterable?
    filterable: false
    # Columns that can be filtered
    filter-on: ~
