# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# User Service Definitions
##
user:
  manage:
    inherit: default
    service: 
      - manage
      - user
    parameters:
      allow: 'user:*'
    
  #
  # Create User Record
  # URL : manage/user/create/{user:name}[?field=value-tuplet[&...]]
  #
  create:
    inherit: 'user:manage'
    action: create
    key: 'user:name'
    parameters:
      exclude: ['user:id', 'user:name']
  #
  # Read User Record
  # URL : 
  # - manage/user/read/{user:id}   or
  # - manage/user/read/{user:name}
  #
  read:    
    inherit: 'user:manage'
    action: read
    keys:
      - 'user:id'
      - 'user:name'
    parameters:
      require: false
      allow: ~
  #
  # Update User Record
  # URL : 
  # - manage/user/update/{user:id}?field=value-tuplet[&...]   or
  # - manage/user/update/{user:name}?field=value-tuplet[&...]
  #
  update:
    inherit: 'user:manage'
    action: update
    keys:
      - 'user:id'
      - 'user:name'
    parameters:
      require: true
      allow: ~
      exclude: ['user:id', 'user:password']
  #
  # Update User Password
  # URL : 
  # - manage/user/update/{user:id}?password=value   or
  # - manage/user/update/{user:name}?password=value
  #
  update-password:
    inherit: 'user:manage'
    action: update
    keys:
      - 'user:id'
      - 'user:name'
    parameters:
      require: true
      allow: 'user:password'
      exclude: 'user:*'
  #
  # Delete User Record
  # URL : 
  # - manage/user/delete/{user:id}   or
  # - manage/user/delete/{user:name}
  #
  delete:
    inherit: 'user:manage'
    action: delete
    keys:
      - 'user:id'
      - 'user:name'
    parameters:
      allow: none
  #
  # List User Records
  # URL : 
  # - manage/users/list[?field=value-tuplet[&...]]
  #
  list: 
    inherit: 'user:manage'
    service: 
      - manage
      - users
    action: list
    parameters: 
      allow: ['virtual:filter','virtual:sort','virtual:limit']
  #
  # Count User Records
  # URL : 
  # - manage/users/count[?field=value-tuplet[&...]]
  #
  count:
    inherit: 'user:manage'
    service: 
      - manage
      - users
    action: count
    parameters:
      allow: ['virtual:filter']
    