# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Step Lists Definition
##
steps:
  #
  # List All Steps for a Set
  #
  test:
    inherit: default
    key: ['test:id']
    services:
      list: 'steps:list({test:id})'
      count: 'steps:count({test:id})'
    display: 'teststep:name'
    fields:
      - 'teststep:sequence'
      - 'teststep:name'
  #
  # List All Possible States for a Step
  #
  states:
    inherit: default
    key: 'state:state'
    services:
      list: 'state:list_states{1}'
      count: 'state:count_states{1}'
    display: 'state:s_description'
    fields:
      - 'state:state'
      - 'state:s_description'
  #
  # List All Possible States Codes for a Step
  #
  codes:
    inherit: default
    key: 'statecode:code'
    services:
      list: 'state:list_state_codes{1,{statecode:state}}'
      count: 'state:count_state:codes{1,{statecode:state}}'
    display: 'state:s_description'
    fields:
      - 'statecode:code'
      - 'statecode:s_description'
