# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Organization Entity (Properties Metadata)
##
organization:
  id: 
    inherit: ':key_sequence'
    data-direction: in
    label: ID
    description: Unique Organization Identifier
  name:
    inherit: ':key'
    label: Name
    description: Unique Organization Name
  description:
    inherit: default
    label: Description
    description: Organization Information
    value: 
      type: html
  creator:
    inherit: ':reference'
    label: Creator
    description: User that created this organization
    value: 
      auto: true
      nullable: false
    reference:
      object: user
      key: user:id
    display:
      field: 'user:name'
  date_created:
    inherit: ':required'
    label: Created
    description: User Password
    value: 
      type: datetime
      auto: true
      nullable: false
  last_modifier:
    inherit: ':reference'
    label: Last Modifier
    description: User that last modified this organization
    value: 
      auto: true
    reference:
      object: user
      key: user:id
    display:
      field: 'user:name'
  date_modified:
    inherit: default
    label: Last Modified
    description: Last Modification Date
    value: 
      type: datetime
      auto: true
    