# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# StateCode Entity (Properties Metadata)
##
statecode:
  id: 
    inherit: ':key_sequence'
    data-direction: in
    label: ID
    description: Unique State Identifier
  state:
    inherit: ':reference'
    label: State
    description: State Associated with this Code
    value: 
      auto: true
      nullable: false
    reference:
      object: state
      key: state:id
    display:
      field: 'state:s_description'
  code: 
    inherit: ':required'
    label: State Code
    description: State Code
    value: 
      type: integer
      nullable: false
  s_description:
    inherit: ':required'
    label: Short Description
    description: Short State Description
    value: 
      nullable: false
  l_description:
    inherit: default
    label: Long Description
    description: Long State Description
    value: 
      type: html
  creator:
    inherit: ':reference'
    label: Creator
    description: User that created this Test Set
    value: 
      auto: true
      nullable: false
    reference:
      object: user
      key: user:id
    display:
      field: 'user:name'
  date_created:
    inherit: ':required'
    label: Created
    description: Creation Date
    value: 
      type: datetime
      auto: true
  last_modifier:
    inherit: ':reference'
    label: Last Modifier
    description: User that last modified this Test Set
    value: 
      auto: true
    reference:
      object: user
      key: user:id
    display:
      field: 'user:name'
  date_modified:
    inherit: default
    label: Last Modified
    description: Last Modification Date
    value: 
      type: datetime
      auto: true
