# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Test Set Service Definitions
##
run:
  #
  # Defaults for Run Management
  #
  testing:
    inherit: default
    service: 
      - testing
      - run
    parameters:
      allow: 'run:*'
      exclude: ['run:id', 'run:creator', 'run:date_created', 'run:last_modifier', 'run:date_modified', 'run:owner', project:*']
  #
  # Defaults for Playing a Run
  #
  testing:
    inherit: default
    service: 
      - testing
      - run
  #
  # Defaults for Run Listings
  #
  listing:
    inherit: default
    service: 
      - testing
      - runs
    parameters: 
      allow: ['virtual:filter','virtual:sort','virtual:limit']
  #
  # Create Run Within the Current Session Project
  # URL :
  # - testing/run/create/{set:id}/{run:name}[?field=value-tuplet[&...]]
  #
  create:
    inherit: 'run:manage'
    action: create
    key: ['set:id', 'run:name']
  #
  # Read Run Record
  # URL : 
  # - testing/run/read/{run:id}  
  #
  read:    
    inherit: 'run:manage'
    action: read
    key: 'run:id'
    parameters:
      allow: ~
      exclude: ~
  #
  # Update Run Record
  # URL : 
  # - testing/run/update/{run:id}?field=value-tuplet[&...]   
  #
  update:
    inherit: 'run:manage'
    action: update
    key: 'run:id'
    parameters:
      require: true
  #
  # Delete Run Record
  # URL : 
  # - testing/run/delete/{run:id}   
  #
  delete:
    inherit: 'run:manage'
    action: delete
    key: 'run:id'
    parameters:
      allow: ~
      exclude: ~
  #
  # Open a Run
  # URL : 
  # - testing/run/open[/{run:id}]
  #
  open:
    inherit: 'run:testing'
    action: open
    key: 
     - 'run:id': ~
  #
  # Close a Run
  # URL : 
  # - testing/run/close[/{run:id}]
  #
  close:
    inherit: 'run:testing'
    action: close
    key: 
      - 'run:id': ~
  #
  # Gets the Run's State
  # URL :
  # - testing/run/state/get[/{run:id}]
  #
  get_state:
    inherit: 'run:testing'
    service: [ 'testing', 'run', 'state' ]
    action: get
  #
  # Set the Run's State
  # URL :
  # - testing/run/state/set/{run:id}/{run:state}[/{run:state_code}]
  #
  set_state:
    inherit: 'run:get_state'
    action: set
    key: 
      - 'run:id' 
      - 'run:state' 
      - 'run:state_code' : 0
  #
  # List All Runs for Current Session Project
  # URL : 
  # - testing/runs/list[?field=value-tuplet[&...]]
  #
  list: 
    inherit: 'run:listing'
    action: list
  #
  # Count All Runs for Current Session Project
  # URL : 
  # - testing/runs/count[?field=value-tuplet[&...]]
  #
  count:
    inherit: 'run:listing'
    action: count
    parameters:
      allow: ['virtual:filter']
  #
  # List Runs for Current Session Project, Owned by the Current Session User
  # URL : 
  # - testing/runs/user/list[?field=value-tuplet[&...]]
  #
  user_set_list: 
    inherit: 'run:list'
    service: 
      - testing
      - runs
      - user
  #
  # Count Runs for Current Session Project, Owned by the Current Session User
  # URL : 
  # - testing/runs/user/count[?field=value-tuplet[&...]]
  #
  user_run_count:
    inherit: 'run:count'
    service: 
      - testing
      - runs
      - user
