# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Organization Table (Metadata Model)
##
organization:
  #
  # Default Organization Table (Model)
  #
  default:
    inherit: default
    title: Organization List
    services:
      list: 'organization:list'
      count: 'organization:count'
    fields:
      - 'organization:id'
      - 'organization:name'
      - 'virtual:filter'
      - 'virtual:sort'
      - 'virtual:limit'
    columns:
      - 'organization:id'
      - 'organization:name'
    hidden:
      - 'organization:id'
    sort-on:
      - 'organization:id'
      - 'organization:name'
    filter-on:
      - 'organization:id'
      - 'organization:name'
  #
  # Organization Management Table (Model)
  #
  manage:
    inherit: 'organization:default'
    title: Organization Management
    actions:
      create:
        label: 'New Organization'
        shortcut: 'CTRL+N'
        icon: 'resource/tc/user_add.png'
        form: 'organization:create'
      edit:
        label: 'Modify Organization'
        shortcut: 'CTRL+E'
        icon: 'resource/tc/user_edit.png'
        form: 'organization:update'
        parameters: 'organization:id'
      display:
        label: 'Organization Information'
        shortcut: 'CTRL+I'
        icon: 'resource/tc/user.png'
        form: 'organization:read'
        parameters: 'organization:id'
      delete:
        label: 'Delete Organization'
        shortcut: 'CTRL+D'
        icon: 'resource/tc/user_delete.png'
        service: 'organization:delete'
