# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Test Set Service Definitions
##
set:
  #
  # Defaults for Test Set Management
  #
  manage:
    inherit: default
    service: 
      - testing
      - set
    parameters:
      allow: 'set:*'
      exclude: ['set:id', 'set:creator', 'set:date_created', 'set:last_modifier', 'set:date_modified', 'set:owner', project:*']
  #
  # Defaults for Test Set Listings
  #
  listing:
    inherit: default
    service: 
      - testing
      - sets
    parameters: 
      allow: ['virtual:filter','virtual:sort','virtual:limit']
  #
  # Create Test Set Within the Current Session Project
  # URL :
  # - testing/set/create/{set:name}[?field=value-tuplet[&...]]
  #
  create:
    inherit: 'set:manage'
    action: create
    key: 'set:name'
  #
  # Read Test Set Record
  # URL : 
  # - testing/set/read/{set:id}  
  #
  read:    
    inherit: 'set:manage'
    action: read
    key: 'set:id'
    parameters:
      allow: ~
      exclude: ~
  #
  # Update Test Set Record
  # URL : 
  # - testing/set/update/{set:id}?field=value-tuplet[&...]   
  #
  update:
    inherit: 'set:manage'
    action: update
    key: 'set:id'
    parameters:
      require: true
  #
  # Modify Test Set State
  # URL : 
  # - testing/set/state/set/{test:id}/{test:state}   
  #
  modify_state:
    inherit: 'set:manage'
    service: 
      - testing
      - set
      - state
    action: set
    key: [ 'set:id', 'set:state' ]
    parameters:
      allow: ~
      exclude: ~
  #
  # Modify Test Set Owner
  # URL : 
  # - testing/set/owner/set/{test:id}/{user:id}   
  #
  modify_owner:
    inherit: 'set:manage'
    service: 
      - testing
      - set
      - owner
    action: set
    key: [ 'set:id', 'set:id' ]
    parameters:
      allow: ~
      exclude: ~
  #
  # Delete Test Set Record
  # URL : 
  # - testing/set/delete/{set:id}   
  #
  delete:
    inherit: 'set:manage'
    action: delete
    key: 'set:id'
    parameters:
      allow: ~
      exclude: ~
  #
  # List All Test Sets for Current Session Project
  # URL : 
  # - testing/sets/list[?field=value-tuplet[&...]]
  #
  list: 
    inherit: 'set:listing'
    action: list
  #
  # Count All Test Sets for Current Session Project
  # URL : 
  # - testing/sets/count[?field=value-tuplet[&...]]
  #
  count:
    inherit: 'set:listing'
    action: count
    parameters:
      allow: ['virtual:filter']
  #
  # List Tests Sets for Current Session Project, Owned by the Current Session User
  # URL : 
  # - testing/sets/user/list[?field=value-tuplet[&...]]
  #
  user_set_list: 
    inherit: 'set:list'
    service: 
      - testing
      - tests
      - user
  #
  # Count Test Sets for Current Session Project, Owned by the Current Session User
  # URL : 
  # - testing/sets/user/count[?field=value-tuplet[&...]]
  #
  user_set_count:
    inherit: 'set:count'
    service: 
      - testing
      - tests
      - user
