# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Test Entity Forms (Metadata Model)
##
test:
  #
  # Default Test FORM (Model)
  #
  default:
    inherit: default
    title: Test
    fields: 
      'Information': ['test:id']
      'Grouping': ['test:group', 'test:name']
      'Description': ['test:description']
    services:
      create: 'test:create'
      read: 'test:read'
      update: 'test:update'
  #
  # Create Test Form
  #
  create:
    inherit: 'test:default'
    title: Create Test
  #
  # Test Details Form
  #
  read:
    inherit: 'test:default'
    title: Test Details
    services:
      create: ~
      update: ~
  #
  # Test Update Form
  #
  update:
    inherit: 'test:default'
    title: Modify Test
    services:
      create: ~
  #
  # Test Modify State
  #
  modify_state:
    inherit: 'test:default'
    title: Modify Test State
    fields: 
      'Information': ['test:id']
      'Grouping': ['test:group', 'test:name']
      'State': ['test:state']
    services:
      update: 'test:modify_state'

  #
  # Test Modify Owner
  #
  modify_owner:
    inherit: 'test:default'
    title: Modify Test's Owner
    fields: 
      'Information': ['test:id']
      'Grouping': ['test:group', 'test:name']
      'Owner': ['user:id']
    services:
      update: 'test:modify_owner'
