# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Organizaton Entity CRUD Forms (Metadata Model)
##
organization:
  #
  # Default Organization FORM (Model)
  #
  default:
    inherit: default
    title: Organization Information
    data-direction: both    
    layout: 
      'Information': ['organization:id', 'organization:name']
      'Description': ['organization:description']
    services:
      read: 'organization:read'
  #
  # Create Organization Form
  #
  create:
    inherit: 'organization:default'
    title: Create Organization
    services:
      create: 'organization:create'
      update: 'organization:update'
  #
  # Organization Details Form
  #
  read:
    inherit: 'organization:default'
    in: 'organization:id'
    title: Organization Details
  #
  # Organization Update Form
  #
  update:
    inherit: 'organization:default'
    in: 'organization:id'
    title: Modify Organization
    services:
      update: 'organization:update'
