# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Test Entity Forms (Metadata Model)
##
test:
  #
  # Base Test Set Details Form
  #
  details:
    inherit: default
    title: Test Details
    layout: 
      'Information': ['test:id']
      'Grouping': ['test:group', 'test:name']
      'Description': ['test:description']
    services:
      create: 'test:create'
  #
  # Create Test Details Form
  #
  create_details:
    inherit: 'test:details'
    services:
      create: 'test:create'
  #
  # Display Test Set Details Form
  #
  display_details:
    inherit: 'test:details'
    in: 'test:id'
    services:
      read: 'test:read'
  #
  # Modify Test Set Details Form
  #
  modify_details:
    inherit: 'test:display_details'
    services:
      update: 'test:update'
  #
  # Test Modify State
  #
  state_modify:
    inherit: 'test:default'
    title: Modify Test State
    in: 'test:id'
    layout: 
      'Information': ['test:id']
      'Grouping': ['test:group', 'test:name']
      'State': 'list\tests:list_states'
    services:
      update: 'test:modify_state'
    field_map:
      'test:state': 'state:state'
  #
  # Test Modify Owner
  #
  owner_modify:
    inherit: 'test:default'
    title: Modify Test's Owner
    in: 'test:id'
    layout: 
      'Information': ['test:id']
      'Grouping': ['test:group', 'test:name']
      'Owner': 'list\project:list_users'
    services:
      update: 'test:modify_owner'
    field_map:
      'test:owner\user:id':        'user:id'
      'test:project\project:id':  'project:id'
  #
  # Modify Step Details
  #
  step_modify:
    inherit: default
    title: Modify Test's Owner
    in: 'teststep'
    layout: 
      'Information': ['teststep:name']
      'Description': ['teststep:description']
  #
  # Display Step Details
  #
  step_details:
    inherit: default
    title: Modify Test's Owner
    in: 'teststep'
    layout: 
      'Key': ['teststep:id']
      'Grouping': ['teststep:sequence', 'teststep:name']
      'Description': ['teststep:description']
  #
  # Steps
  #
  steps_details:
    inherit: default
    in: 'test:id'
    title: Display Steps
    layout: 
      'Steps': 'list\steps:test'
  #
  # Steps
  #
  steps_manage:
    inherit: ':table'
    title: Manage Steps
    layout: 
      'Steps': 'table\step:manage'
  #
  # Create Test Form
  #
  create:
    inherit: ':tabbed'
    title: Create Test
    tabs: 
      - 'test:create_details': Details
      - 'test:steps_manage' : Steps
  #
  # Display Test Form
  #
  read:
    inherit: ':tabbed'
    in: 'test:id'       
    title: Test Details
    tabs: 
      - 'test:display_details': Details
      - 'test:steps_details' : Steps
  #
  # Update Test Form
  #
  update:
    inherit: ':tabbed'
    in: 'set:id'       
    title: Modify Test
    tabs: 
      - 'test:modify_details': Details
      - 'test:steps_manage' : Steps
