# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Default Table (Metadata Model)
##
tables:
  default:
    default:
      # Specifies the Parent Table, in the inheritance hierarchy, for this table
      #
      # (OPTIONAL)
      #
      # Elements:
      # - TEXT: table_id
      inherit: ~
      # Title for the Table
      #
      # (REQUIRED)
      #
      # Elements:
      # - TEXT
      title: 'Title'
      # Associates a Recognized Meta Form, Service Alias, with a specific
      # Service Meta Entry 
      #
      # (REQUIRED)
      #
      # Elements:
      #   MAP: ( service_alias -> (SERVICE META) service_id)
      #   Recognized Aliases: One of (list, count)
      #   In the Future when inline editing allowed (create, read, update, delete)
      services: ~
      # Specifies All the Fields that will be used (including fields used int
      # service calls, etc.)
      #
      # (REQUIRED)
      #
      # Elements: (One Of)
      # - TEXT: field_id              - A Single Field Table
      # - ARRAY(TEXT: field_id, ....) - Normal Multi-field Table
      fields: ~
      # Specifies the Fields that will be used to build the Table Row 
      # (in the order of initial use)
      #
      # (OPTIONAL: If not Provided 'fields' will be used)
      #
      # Elements: (One Of)
      # - TEXT: field_id              - A Single Field Table
      # - ARRAY(TEXT: field_id, ....) - Normal Multi-field Table
      columns: ~
      # Specifies the Fields that are initially hidden from the Table Display
      # but can be added to the display by the user
      #
      # (OPTIONAL)
      #
      # Elements: (One Of)
      # - TEXT: field_id              - A Single Field Table
      # - ARRAY(TEXT: field_id, ....) - Normal Multi-field Table
      hidden: ~
      # Specifies the Fields that can be used to sort the Table Data Set.
      # If not specified (i.e. == NULL) then the table does not allow sorting.
      #
      # (OPTIONAL: DEFAULT == NULL)
      #
      # Elements: (One Of)
      # - TEXT: field_id              - A Single Field Table
      # - ARRAY(TEXT: field_id, ....) - Normal Multi-field Table
      sort-on: ~
      # Specifies the Fields that can be used for filtering the Table Data Set
      # If not specified (i.e. == NULL) then the table does not allow filtering.
      #
      # (OPTIONAL: DEFAULT == NULL)
      #
      # Elements: (One Of)
      # - TEXT: field_id              - A Single Field Table
      # - ARRAY(TEXT: field_id, ....) - Normal Multi-field Table
      filter-on: ~
      # Table Specific Action Definitions
      #
      # (OPTIONAL: MAP)
      #
      # Elements:
      #   actions : Action Definition
      #            (OPTIONAL: MAP: (action_id -> ...)
      actions: ~
      # Table Specific Transformations 
      #
      # (OPTIONAL: MAP)
      #
      # Elements:
      #   fields : Per Field transformations, which are to modify the Field Value Displayed
      #            (OPTIONAL: MAP: (field_id -> TEXT: transformation EL, ...)
      transformations: ~
