# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Test Step Entity (Properties Metadata)
##
step:
  default: 
    inherit: default
    data-direction: both
  id: 
    inherit: default:key
    data-direction: in
    label: ID
    description: Unique Step Identifier
    value: 
      type: integer
      auto: true
  test:
    inherit: ':reference'
    label: Test
    description: TEst the Step Belongs To
    value: 
      auto: true
    reference:
      object: test
      key: test:id
    display:
      field: 'test:name'
  sequence: 
    inherit: default:default
    label: Sequence
    description: Step Sequence Number in Test
    value: 
      type: integer
  name:
    inherit: step:default
    label: Name
    description: Step Name
  description:
    inherit: project:default
    label: Description
    description: Project Information
    value: 
      type: html
    