# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Organization Management
##

# Create
orgs_create:
    pattern:  /create/{name}
    defaults: { _controller: TestCenterServiceBundle:Organizations:create, name: null }

# Read (By Name or ID)
orgs_read_id:
    pattern:  /read/{id}
    defaults: { _controller: TestCenterServiceBundle:Organizations:read }
    requirements:
        id:  \d+
  
orgs_read_name:
    pattern:  /read/{name}
    defaults: { _controller: TestCenterServiceBundle:Organizations:readByName }
        
# Update
orgs_update:
    pattern:  /update/{id}
    defaults: { _controller: TestCenterServiceBundle:Organizations:update }
    requirements:
        id:  \d+
    
orgs_update_name:
    pattern:  /update/{name}
    defaults: { _controller: TestCenterServiceBundle:Organizations:updateByName }
    
# Delete (A Single or All Organizations : id == null)
orgs_delete:
    pattern:  /delete/{id}
    defaults: { _controller: TestCenterServiceBundle:Organizations:delete, id: null }
    requirements:
        id:  \d+

orgs_delete_name:
    pattern:  /delete/{name}
    defaults: { _controller: TestCenterServiceBundle:Organizations:deleteByName }

# List Organizations (The Results will depend on the user that is logged in, and the the users permissions)
orgs_list:
    pattern:  /list/{filter}/{sort}/{limit}
    defaults: { _controller: TestCenterServiceBundle:Organizations:list, filter: null, sort: null, limit: null  }

# Number of Organizations (The Results will depend on the user that is logged in, and the the users permissions)
# (i.e. the count, should return the number of orgs, that would be listed)
orgs_count:
    pattern:  /count/{filter}
    defaults: { _controller: TestCenterServiceBundle:Organizations:count, filter: null }

##
# Organization User Management
##
tc_org_users:
    resource: "@TestCenterServiceBundle/Resources/config/org_users.yml"
    prefix:   /user

##
# Organization Project Management
##
tc_org_projects:
    resource: "@TestCenterServiceBundle/Resources/config/org_projects.yml"
    prefix:   /projects

##
# Organization Document Management
##

# Add Document to Organization
orgs_doc_add:
    pattern:  /doc/add/{id}
    defaults: { _controller: TestCenterServiceBundle:Documents:orgDocAdd }
    requirements:
        id:       \d+
        user_id:  \d+

# Remove Document from Organization
orgs_doc_remove:
    pattern:  /doc/remove/{id}/{doc_id}
    defaults: { _controller: TestCenterServiceBundle:Documents:orgDocRemove }
    requirements:
        id:       \d+
        user_id:  \d+

# List Documents in the Organization
orgs_doc_list:
    pattern:  /doc/list/{id}
    defaults: { _controller: TestCenterServiceBundle:Documents:orgDocList }
    requirements:
        id:  \d+

# Count Documents in the  Organization
orgs_doc_count:
    pattern:  /doc/count/{id}
    defaults: { _controller: TestCenterServiceBundle:Documents:orgDocCount }
    requirements:
        id:  \d+
