# Test Center - Compliance Testing Application
# Copyright (C) 2012 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Project Container Management (service path /project/container)
##

# Set Current Container to Root Project Container
project_container_root:
    pattern:  /root
    defaults: { _controller: TestCenterServiceBundle:Container:root }

# Change Container (Descend, Ascend if id = null, equivalent to cd ..)
project_container_cd_id:
    pattern:  /cd/{id}
    defaults: { _controller: TestCenterServiceBundle:Container:cdById, id: null }
    requirements:
        id:  \d+

# Change Container (Descend)
project_container_cd_name:
    pattern:  /cd/{name}
    defaults: { _controller: TestCenterServiceBundle:Container:cdByName }

# Current Working Directory
project_container_cwd:
    pattern:  /cwd
    defaults: { _controller: TestCenterServiceBundle:Container:cwd }

# Make Directory (Create Container)
project_container_mkdir:
    pattern:  /mkdir/{name}
    defaults: { _controller: TestCenterServiceBundle:Container:mkdir }

# List Elements in Container (Alias for ls)
project_container_dir:
    pattern:  /dir
    defaults: { _controller: TestCenterServiceBundle:Container:ls }

# Same as dir
project_container_ls:
    pattern:  /ls
    defaults: { _controller: TestCenterServiceBundle:Container:ls }

# Number of Items in the Container
project_container_count:
    pattern:  /count
    defaults: { _controller: TestCenterServiceBundle:Container:count }
