# Test Center - Compliance Testing Application
# Copyright (C) 2012 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Project Management
##

# Create (Within a Specific Organization)
project_create:
    pattern:  /create/{org_id}/{name}
    defaults: { _controller: TestCenterServiceBundle:Projects:createInOrg, name: null }
    requirements:
        org_id:  \d+

# Read (By Name or ID)
project_read_id:
    pattern:  /read/{id}
    defaults: { _controller: TestCenterServiceBundle:Projects:read }
    requirements:
        id:  \d+

project_read_name:
    pattern:  /read/{name}
    defaults: { _controller: TestCenterServiceBundle:Projects:readByName }

# Update
project_update:
    pattern:  /update/{id}
    defaults: { _controller: TestCenterServiceBundle:Projects:update }
    requirements:
        id:  \d+

project_update_name:
    pattern:  /update/{name}
    defaults: { _controller: TestCenterServiceBundle:Projects:updateByName }

# Delete (A Single or All Projects : id == null)
project_delete:
    pattern:  /delete/{id}
    defaults: { _controller: TestCenterServiceBundle:Projects:delete, id: null }
    requirements:
        id:  \d+

project_delete_name:
    pattern:  /delete/{name}
    defaults: { _controller: TestCenterServiceBundle:Projects:deleteByName }

# List Projects (Global - All Projects Independently of the Organization They Belong To)
project_list:
    pattern:  /list/{filter}/{sort}/{limit}
    defaults: { _controller: TestCenterServiceBundle:Projects:list, filter: null, sort: null, limit: null  }

# Projects Count (Global - All Projects Independently of the Organization They Belong To)
project_count:
    pattern:  /count/{filter}
    defaults: { _controller: TestCenterServiceBundle:Projects:count, filter: null }

##
# Project User Management
##
tc_project_users:
    resource: "@TestCenterServiceBundle/Resources/config/project_users.yml"
    prefix:   /users

##
# Project Container Management
##
tc_project_containers:
    resource: "@TestCenterServiceBundle/Resources/config/project_container.yml"
    prefix:   /container

##
# Project Test Management
##
tc_project_tests:
    resource: "@TestCenterServiceBundle/Resources/config/project_test.yml"
    prefix:   /test

##
# Project TestSet Management
##
tc_project_sets:
    resource: "@TestCenterServiceBundle/Resources/config/project_set.yml"
    prefix:   /set

##
# Project TestSet Management
##
tc_project_runs:
    resource: "@TestCenterServiceBundle/Resources/config/project_runs.yml"
    prefix:   /runs
