# Test Center - Compliance Testing Application
# Copyright (C) 2012 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Project Test Management (service path /project/test)
##

# Create (Within a Session Project and Working Container)
project_test_create:
    pattern:  /create/{name}/{fv_settings}
    defaults: { _controller: TestCenterServiceBundle:Tests:create, fv_settings: null }

# Read (By Name or ID)
project_test_read_id:
    pattern:  /read/{id}
    defaults: { _controller: TestCenterServiceBundle:Tests:read }
    requirements:
        id:  \d+

project_test_read_name:
    pattern:  /read/{name}
    defaults: { _controller: TestCenterServiceBundle:Tests:readByName }

# Update
project_test_update:
    pattern:  /update/{id}/{fv_settings}
    defaults: { _controller: TestCenterServiceBundle:Tests:update }
    requirements:
        id:  \d+

# Delete (A Single or All Projects : id == null)
project_test_delete:
    pattern:  /delete/{id}
    defaults: { _controller: TestCenterServiceBundle:Tests:delete, id: null }
    requirements:
        id:  \d+

# List Tests 
project_test_list:
    pattern:  /list/{container_id}
    defaults: { _controller: TestCenterServiceBundle:Tests:listContainer, container_id: null  }
    requirements:
        container_id:  \d+

# Number of Tests 
project_test_count:
    pattern:  /count/{container_id}
    defaults: { _controller: TestCenterServiceBundle:Tests:countContainer, container_id: null  }
    requirements:
        container_id:  \d+

##
# Test Step Management (service path /project/test/step)
##

# Add Link to Test
project_test_step_add:
    pattern:  /step/add/{test_id}/{title}/{sequence}/{fv_settings}
    defaults: { _controller: TestCenterServiceBundle:TestSteps:create, sequence: null, fv_settings: null }
    requirements:
        test_id:  \d+
        sequence:  \d+

# Read
project_test_step_read_id:
    pattern:  /step/read/{test_id}/{sequence}
    defaults: { _controller: TestCenterServiceBundle:TestSteps:read }
    requirements:
        id:  \d+
        sequence:  \d+

# Update
project_test_step_update:
    pattern:  /step/update/{test_id}/{sequence}/{fv_settings}
    defaults: { _controller: TestCenterServiceBundle:TestSteps:update }
    requirements:
        id:  \d+

# Remove Link to Test (if test_id == null, remove all tests)
project_test_step_remove:
    pattern:  /step/remove/{test_id}/{sequence}
    defaults: { _controller: TestCenterServiceBundle:TestSteps:delete}
    requirements:
        test_id:  \d+
        sequence:  \d+

# Renumber Links in TestSet
project_test_step_renumber:
    pattern:  /step/renumber/{test_id}/{step}
    defaults: { _controller: TestCenterServiceBundle:TestSteps:stepRenumber}
    requirements:
        test_id:  \d+
        step:  \d+

# Renumber Links in TestSet
project_test_step_move:
    pattern:  /step/move/{test_id}/{sequence}/{to}
    defaults: { _controller: TestCenterServiceBundle:TestSteps:stepMove}
    requirements:
        test_id:  \d+
        sequence:  \d+
        to:  \d+

# List Links 
project_test_step_list:
    pattern:  /step/list/{test_id}
    defaults: { _controller: TestCenterServiceBundle:TestSteps:stepList}
    requirements:
        test_id:  \d+

# Number of Link 
project_test_step_count:
    pattern:  /step/count/{test_id}
    defaults: { _controller: TestCenterServiceBundle:TestSteps:stepCount}
    requirements:
        test_id:  \d+
