# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Project TestSet Management (service path /project/set)
##

# Create (Within a Session Project and Working Container)
project_sets_create:
    pattern:  /create/{name}/{fv_settings}
    defaults: { _controller: TestCenterServiceBundle:TestSets:create, fv_settings: null }

# Read (By Name or ID)
project_sets_read_id:
    pattern:  /read/{id}
    defaults: { _controller: TestCenterServiceBundle:TestSets:read }
    requirements:
        id:  \d+

project_sets_read_name:
    pattern:  /read/{name}
    defaults: { _controller: TestCenterServiceBundle:TestSets:readByName }

# Update
project_sets_update:
    pattern:  /update/{id}/{fv_settings}
    defaults: { _controller: TestCenterServiceBundle:TestSets:update }
    requirements:
        id:  \d+

# Delete (A Single or All Projects : id == null)
project_sets_delete:
    pattern:  /delete/{id}
    defaults: { _controller: TestCenterServiceBundle:TestSets:delete, id: null }
    requirements:
        id:  \d+

# List Tests 
project_sets_list:
    pattern:  /list/{container_id}
    defaults: { _controller: TestCenterServiceBundle:TestSets:listContainer, container_id: null  }
    requirements:
        container_id:  \d+

# Number of Tests 
project_sets_count:
    pattern:  /count/{container_id}
    defaults: { _controller: TestCenterServiceBundle:TestSets:countContainer, container_id: null  }
    requirements:
        container_id:  \d+

##
# TestSet Link Management (service path /project/set/link)
##

# Add Link to Test
project_sets_link_add:
    pattern:  /link/add/{id}/{test_id}/{sequence}
    defaults: { _controller: TestCenterServiceBundle:TestSets:linkAdd, sequence: null  }
    requirements:
        id:  \d+
        test_id:  \d+
        sequence:  \d+

# Remove Link to Test (if test_id == null, remove all tests)
project_sets_link_remove:
    pattern:  /link/remove/{id}/{test_id}
    defaults: { _controller: TestCenterServiceBundle:TestSets:linkRemove, test_id: null}
    requirements:
        id:  \d+
        test_id:  \d+

# Renumber Links in TestSet
project_sets_link_renumber:
    pattern:  /link/renumber/{id}/{step}
    defaults: { _controller: TestCenterServiceBundle:TestSets:linkRenumber}
    requirements:
        id:  \d+
        step:  \d+

# Renumber Links in TestSet
project_sets_link_move:
    pattern:  /link/move/{id}/{sequence}/{to}
    defaults: { _controller: TestCenterServiceBundle:TestSets:linkMove}
    requirements:
        id:  \d+
        sequence:  \d+
        to:  \d+

# List Links 
project_sets_link_list:
    pattern:  /link/list/{id}
    defaults: { _controller: TestCenterServiceBundle:TestSets:linkList}
    requirements:
        id:  \d+

# Number of Link 
project_sets_link_count:
    pattern:  /link/count/{id}
    defaults: { _controller: TestCenterServiceBundle:TestSets:linkCount}
    requirements:
        id:  \d+
