# Test Center - Compliance Testing Application
# Copyright (C) 2012 - 2013 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# User Management
##

# Create
users_create:
    pattern:  /create/{name}
    defaults: { _controller: TestCenterServiceBundle:Users:create, name: null}

# Read (By Name or ID)
users_read_id:
    pattern:  /read/{id}
    defaults: { _controller: TestCenterServiceBundle:Users:read }
    requirements:
        id:  \d+
  
users_read_name:
    pattern:  /read/{name}
    defaults: { _controller: TestCenterServiceBundle:Users:readByName }
        
# Update
users_update:
    pattern:  /update/{id}
    defaults: { _controller: TestCenterServiceBundle:Users:update }
    requirements:
        id:  \d+

users_update_name:
    pattern:  /update/{name}
    defaults: { _controller: TestCenterServiceBundle:Users:updateByName }
    
# Delete 
users_delete:
    pattern:  /delete/{id}
    defaults: { _controller: TestCenterServiceBundle:Users:delete }
    requirements:
        id:  \d+

users_delete_name:
    pattern:  /delete/{name}
    defaults: { _controller: TestCenterServiceBundle:Users:deleteByName }

# List Users (The Results will depend on the wether the user is logged in or not, and the the users permissions)
users_list:
    pattern:  /list/{filter}/{sort}/{limit}
    defaults: { _controller: TestCenterServiceBundle:Users:list, filter: null, sort: null, limit: null }
    requirements:
        limit:  \d+

# Number of Users (The Results will depend on the wether the user is logged in or not, and the the users permissions)
# (i.e. the count, should return the number of users, that would be listed)
users_count:
    pattern:  /count/{filter}
    defaults: { _controller: TestCenterServiceBundle:Users:count, filter: null }

##
# User Organization Management  (service path /users/orgs)
##
tc_user_orgs:
    resource: "@TestCenterServiceBundle/Resources/config/user_orgs.yml"
    prefix:   /org


##
# Users Project Management  (service path /users/projects)
##
tc_user_projects:
    resource: "@TestCenterServiceBundle/Resources/config/user_projects.yml"
    prefix:   /projects
