# Test Center - Compliance Testing Application
# Copyright (C) 2012 Paulo Ferreira <pf at sourcenotes.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

##
# Users Project Management  (service path /users/projects)
##

# Add User to Project (Requires User to Belong to Projects Organization)
users_project_add:
    pattern:  /add/{user_id}/{project_id}/{permissions}
    defaults: { _controller: TestCenterServiceBundle:UserProject:link, permissions: null }
    requirements:
        user_id:  \d+
        project_id:  \d+

# Remove User from Project
users_project_remove:
    pattern:  /remove/{user_id}/{project_id}
    defaults: { _controller: TestCenterServiceBundle:UserProject:unlink }
    requirements:
        user_id:  \d+
        project_id:  \d+

# Get User's Project Settings
users_project_get:
    pattern:  /get/{user_id}/{project_id}
    defaults: { _controller: TestCenterServiceBundle:UserProject:get }
    requirements:
        user_id:  \d+
        project_id:  \d+

# Set User's Project Settings
users_project_set:
    pattern:  /set/{user_id}/{project_id}/{permissions}
    defaults: { _controller: TestCenterServiceBundle:UserProject:set }
    requirements:
        user_id:  \d+
        project_id:  \d+

# List Users in the Project
users_project_list:
    pattern:  /list/{user_id}
    defaults: { _controller: TestCenterServiceBundle:UserProject:projectList }
    requirements:
        user_id:  \d+

# Count Users in the  Project
users_project_count:
    pattern:  /count/{user_id}
    defaults: { _controller: TestCenterServiceBundle:UserProject:projectCount }
    requirements:
        user_id:  \d+
