<?php

namespace TestCenter\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StateCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateCodeRepository extends EntityRepository
{
}